import cache from '../data/wikidata.json';

// ---------------------------------------------------------------------------
// Read-side of the build-time Wikidata enrichment.
//
// The cache (src/data/wikidata.json) is regenerated by scripts/enrich-wikidata.mjs
// wherever Wikidata is reachable (CI / Cloudflare). Pages read it through here
// and always fall back gracefully when an entry is missing — so a failed or
// skipped refresh never breaks the build, it just shows less.
//
// Wikidata is CC0 (public domain); we still credit it, and link out to the
// entity and its Wikipedia article, because that is useful reference furniture.
// ---------------------------------------------------------------------------

export interface PersonFacts {
  source?: string;
  qid?: string | null;
  wikipedia?: string;
  dateOfBirth?: string; // ISO yyyy-mm-dd
}

export interface ShowFacts {
  source?: string;
  qid?: string | null;
  wikipedia?: string;
  inception?: number;
  episodes?: number; // maintained by the live refresh; grows over time
}

interface Cache {
  generatedAt: string | null;
  people: Record<string, PersonFacts>;
  shows: Record<string, ShowFacts>;
}

const data = cache as unknown as Cache;

export function factsForPerson(slug: string): PersonFacts | undefined {
  return data.people?.[slug];
}

export function factsForShow(slug: string): ShowFacts | undefined {
  return data.shows?.[slug];
}

/** URL to the Wikidata entity, when its QID is known. */
export function wikidataUrl(qid?: string | null): string | undefined {
  return qid ? `https://www.wikidata.org/wiki/${qid}` : undefined;
}

/** When the enrichment cache was last refreshed (null until the first run). */
export function enrichmentDate(): string | null {
  return data.generatedAt;
}
