import cache from '../data/wikidata.json';

// ---------------------------------------------------------------------------
// Read-side of the build-time Wikidata enrichment.
//
// The cache (src/data/wikidata.json) is regenerated by scripts/enrich-wikidata.mjs
// wherever Wikidata is reachable (CI / Cloudflare). Pages read it through here
// and always fall back gracefully when an entry is missing — so a failed or
// skipped refresh never breaks the build, it just shows less.
//
// Wikidata is CC0 (public domain); we still credit it, and link out to the
// entity and its Wikipedia article, because that is useful reference furniture.
// ---------------------------------------------------------------------------

/** A Commons image the enrichment found, with the credit already assembled.
    A suggestion only — never used without an explicit opt-in. */
export interface ImageSuggestion {
  file: string;
  thumbUrl: string; // external upload.wikimedia.org URL (fallback)
  imageLocal?: string; // committed copy under /images/wikidata/ — preferred
  descriptionUrl?: string;
  credit: string; // "Author · CC BY-SA 4.0 · Wikimedia Commons"
  licence?: string;
  licenceUrl?: string;
}

export interface PersonFacts {
  source?: string;
  qid?: string | null;
  wikipedia?: string;
  dateOfBirth?: string; // ISO yyyy-mm-dd
  imageSuggestion?: ImageSuggestion;
}

export interface ShowFacts {
  source?: string;
  qid?: string | null;
  wikipedia?: string;
  inception?: number;
  episodes?: number; // maintained by the live refresh; grows over time
  imageSuggestion?: ImageSuggestion;
}

interface Cache {
  generatedAt: string | null;
  people: Record<string, PersonFacts>;
  shows: Record<string, ShowFacts>;
}

const data = cache as unknown as Cache;

export function factsForPerson(slug: string): PersonFacts | undefined {
  return data.people?.[slug];
}

export function factsForShow(slug: string): ShowFacts | undefined {
  return data.shows?.[slug];
}

/** URL to the Wikidata entity, when its QID is known. */
export function wikidataUrl(qid?: string | null): string | undefined {
  return qid ? `https://www.wikidata.org/wiki/${qid}` : undefined;
}

/** When the enrichment cache was last refreshed (null until the first run). */
export function enrichmentDate(): string | null {
  return data.generatedAt;
}

// ---------------------------------------------------------------------------
// Image resolution — the approval gate.
//
// A self-hosted `image` always wins. Otherwise the Commons suggestion is used
// ONLY when the entity opted in with `useWikidataImage: true`. Nothing licensed
// is ever shown without that opt-in, and the credit is carried through.
// ---------------------------------------------------------------------------

export interface ResolvedImage {
  src: string;
  alt?: string;
  credit?: string;
  creditUrl?: string;
}

interface EntityImageInput {
  image?: string;
  imageAlt?: string;
  imageCredit?: string;
  useWikidataImage?: boolean;
  name?: string;
  facts?: PersonFacts | ShowFacts;
}

export function resolveEntityImage(input: EntityImageInput): ResolvedImage | undefined {
  // When opted in, a real (credited) Commons image is preferred; a self-hosted
  // `image` is the fallback until the enrichment has one (e.g. before the first
  // refresh, or when Wikidata has no P18 for the entity).
  const suggestion = input.facts?.imageSuggestion;
  if (input.useWikidataImage && suggestion) {
    return {
      // Prefer the committed, self-hosted copy; fall back to the external URL
      // if the download hasn't happened yet.
      src: suggestion.imageLocal ?? suggestion.thumbUrl,
      alt: input.imageAlt ?? input.name,
      credit: suggestion.credit,
      creditUrl: suggestion.descriptionUrl,
    };
  }
  if (input.image) {
    return { src: input.image, alt: input.imageAlt ?? input.name, credit: input.imageCredit };
  }
  return undefined;
}

/**
 * A Commons image suggestion that exists but hasn't been approved yet — for a
 * dev-only review hint. Returns undefined in production, or when there's nothing
 * to suggest, or when an image is already in use.
 */
export function pendingImageSuggestion(input: EntityImageInput): ImageSuggestion | undefined {
  if (!import.meta.env.DEV) return undefined;
  if (input.image || input.useWikidataImage) return undefined;
  return input.facts?.imageSuggestion;
}
